FROM python:3.11-slim

# Herramientas para .doc y utilidades
RUN apt-get update && apt-get install -y --no-install-recommends \
    antiword \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
ENV PYTHONUNBUFFERED=1

CMD ["python", "-u", "app.py"]
